# Generated by Django 5.0.4 on 2024-04-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=200)),
                ('course_credits', models.IntegerField()),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_hod', models.CharField(max_length=50)),
                ('dept_location', models.CharField(choices=[('C-Block', 'Computer Block'), ('M-Block', 'Mechanical Block'), ('R&D Block', 'R&D Block')], max_length=50)),
            ],
            options={
                'db_table': 'department_table',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Prefer not to say')], max_length=10)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='klu123', max_length=100)),
                ('contact', models.BigIntegerField(unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Faculty_registration_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('Mech', 'Mechanical'), ('AI & DS', 'Artificial Intelligence')], max_length=10)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
                ('studentimage', models.FileField(upload_to='studentimages')),
            ],
            options={
                'db_table': 'registration_table',
            },
        ),
        migrations.CreateModel(
            name='Faculty_Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('fk2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'db_table': 'Facultycourse_table',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'db_table': 'Marks_table',
            },
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
